services:
  postgres:
    image: postgres:latest
    container_name: spring-boot-constellation-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: spring-boot-constellation-db
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
